/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#include "gpu_shader_create_info.hh"

/* EEVEE_shaders_effect_motion_blur_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
FRAGMENT_SOURCE("effect_motion_blur_frag.glsl")
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, DEPTH_2D, depthBuffer)
SAMPLER(2, FLOAT_2D, velocityBuffer)
SAMPLER(3, FLOAT_2D, tileMaxBuffer)
PUSH_CONSTANT(FLOAT, depthScale)
PUSH_CONSTANT(IVEC2, tileBufferSize)
PUSH_CONSTANT(VEC2, viewportSize)
PUSH_CONSTANT(VEC2, viewportSizeInv)
PUSH_CONSTANT(BOOL, isPerspective)
PUSH_CONSTANT(VEC2, nearFar)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_motion_blur_object_sh_get */
GPU_SHADER_INTERFACE_INFO(eevee_legacy_motion_object_iface)
SMOOTH(VEC3, currWorldPos)
SMOOTH(VEC3, prevWorldPos)
SMOOTH(VEC3, nextWorldPos)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur_object_common)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
VERTEX_SOURCE("object_motion_vert.glsl")
FRAGMENT_SOURCE("object_motion_frag.glsl")
VERTEX_OUT(eevee_legacy_motion_object_iface)
FRAGMENT_OUT(0, VEC4, outData)
PUSH_CONSTANT(MAT4, currModelMatrix)
PUSH_CONSTANT(MAT4, prevModelMatrix)
PUSH_CONSTANT(MAT4, nextModelMatrix)
PUSH_CONSTANT(MAT4, prevViewProjMatrix)
PUSH_CONSTANT(MAT4, currViewProjMatrix)
PUSH_CONSTANT(MAT4, nextViewProjMatrix)
PUSH_CONSTANT(BOOL, useDeform)
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur_object_hair)
DEFINE("HAIR")
DEFINE("HAIR_SHADER")
ADDITIONAL_INFO(eevee_legacy_hair_lib)
ADDITIONAL_INFO(eevee_legacy_effect_motion_blur_object_common)
SAMPLER(0, FLOAT_BUFFER, prvBuffer)
SAMPLER(1, FLOAT_BUFFER, nxtBuffer)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur_object)
ADDITIONAL_INFO(eevee_legacy_effect_motion_blur_object_common)
VERTEX_IN(0, VEC3, pos)
VERTEX_IN(1, VEC3, prv)
VERTEX_IN(2, VEC3, nxt)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_motion_blur_velocity_tiles_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur_velocity_tiles_common)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
FRAGMENT_SOURCE("effect_velocity_tile_frag.glsl")
SAMPLER(0, FLOAT_2D, velocityBuffer)
PUSH_CONSTANT(VEC2, viewportSize)
PUSH_CONSTANT(VEC2, viewportSizeInv)
PUSH_CONSTANT(IVEC2, velocityBufferSize)
FRAGMENT_OUT(0, VEC4, tileMaxVelocity)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur_velocity_tiles_GATHER)
DEFINE("TILE_GATHER")
ADDITIONAL_INFO(eevee_legacy_effect_motion_blur_velocity_tiles_common)
PUSH_CONSTANT(IVEC2, gatherStep)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_effect_motion_blur_velocity_tiles_EXPANSION)
DEFINE("TILE_EXPANSION")
ADDITIONAL_INFO(eevee_legacy_effect_motion_blur_velocity_tiles_common)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()
