/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#include "gpu_shader_create_info.hh"

/* effect_minmaxz_frag permutation inputs. */
GPU_SHADER_CREATE_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("effect_minmaxz_frag.glsl")
FRAGMENT_OUT(0, VEC4, fragColor) /* Needed by certain drivers. */
DEPTH_WRITE(DepthWrite::ANY)
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minmaxz_layered_common)
DEFINE("LAYERED")
SAMPLER(0, DEPTH_2D_ARRAY, depthBuffer)
PUSH_CONSTANT(INT, depthLayer)
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minmaxz_non_layered_common)
SAMPLER(0, DEPTH_2D, depthBuffer)
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minmaxz_non_copy)
PUSH_CONSTANT(VEC2, texelSize)
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minmaxz_copy)
DEFINE("COPY_DEPTH")
GPU_SHADER_CREATE_END()

/* Permutations. */
GPU_SHADER_CREATE_INFO(eevee_legacy_minz_downlevel)
DEFINE("MIN_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_copy)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_maxz_downlevel)
DEFINE("MAX_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_copy)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minz_downdepth)
DEFINE("MIN_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_copy)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_maxz_downdepth)
DEFINE("MAX_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_copy)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minz_downdepth_layer)
DEFINE("MIN_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_copy)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_maxz_downdepth_layer)
DEFINE("MAX_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_copy)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_maxz_copydepth_layer)
DEFINE("MAX_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_copy)
ADDITIONAL_INFO(eevee_legacy_minmaxz_layered_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_minz_copydepth)
DEFINE("MIN_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_copy)
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_layered_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_maxz_copydepth)
DEFINE("MAX_PASS")
ADDITIONAL_INFO(eevee_legacy_minmaxz_copy)
ADDITIONAL_INFO(eevee_legacy_minmaxz_common)
ADDITIONAL_INFO(eevee_legacy_minmaxz_non_layered_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_update_noise_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_update_noise)
SAMPLER(0, FLOAT_2D, blueNoise)
PUSH_CONSTANT(VEC3, offsets)
FRAGMENT_OUT(0, VEC4, FragColor)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("update_noise_frag.glsl")
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_taa_resolve_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_taa_resolve)
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, colorHistoryBuffer)
FRAGMENT_OUT(0, VEC4, FragColor)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(draw_view)
FRAGMENT_SOURCE("effect_temporal_aa.glsl")
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_taa_resolve_basic)
PUSH_CONSTANT(FLOAT, alpha)
ADDITIONAL_INFO(eevee_legacy_taa_resolve)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_taa_resolve_reprojection)
DEFINE("USE_REPROJECTION")
SAMPLER(2, DEPTH_2D, depthBuffer)
PUSH_CONSTANT(MAT4, prevViewProjectionMatrix)
ADDITIONAL_INFO(eevee_legacy_taa_resolve)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_velocity_resolve_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_velocity_resolve)
SAMPLER(0, DEPTH_2D, depthBuffer)
PUSH_CONSTANT(MAT4, prevViewProjMatrix)
PUSH_CONSTANT(MAT4, currViewProjMatrixInv)
PUSH_CONSTANT(MAT4, nextViewProjMatrix)
FRAGMENT_OUT(0, VEC4, outData)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("effect_velocity_resolve_frag.glsl")
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_downsample_sh_get */

GPU_SHADER_CREATE_INFO(eevee_legacy_downsample_shared)
ADDITIONAL_INFO(draw_fullscreen)
SAMPLER(0, FLOAT_2D, source)
PUSH_CONSTANT(FLOAT, fireflyFactor)
FRAGMENT_OUT(0, VEC4, FragColor)
FRAGMENT_SOURCE("effect_downsample_frag.glsl")
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_downsample)
ADDITIONAL_INFO(eevee_legacy_downsample_shared)
PUSH_CONSTANT(VEC2, texelSize)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_color_copy_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_color_copy)
DEFINE("COPY_SRC")
ADDITIONAL_INFO(eevee_legacy_downsample_shared)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_ambient_occlusion_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_ambient_occlusion)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_ambient_occlusion_lib)
ADDITIONAL_INFO(draw_fullscreen)
SAMPLER(0, FLOAT_2D, normalBuffer)
PUSH_CONSTANT(FLOAT, fireflyFactor)
FRAGMENT_OUT(0, VEC4, FragColor)
FRAGMENT_SOURCE("effect_gtao_frag.glsl")
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_ambient_occlusion_debug_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_ambient_occlusion_debug)
DEFINE("DEBUG_AO")
DEFINE("ENABLE_DEFERED_AO")
ADDITIONAL_INFO(eevee_legacy_ambient_occlusion)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_reflection_trace_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_reflection_trace)
ADDITIONAL_INFO(eevee_legacy_surface_lib_step_raytrace)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_raytrace_lib)
ADDITIONAL_INFO(eevee_legacy_lightprobe_lib)
ADDITIONAL_INFO(eevee_legacy_reflection_lib)
ADDITIONAL_INFO(draw_fullscreen)
SAMPLER(0, FLOAT_2D, normalBuffer)
SAMPLER(1, FLOAT_2D, specroughBuffer)
PUSH_CONSTANT(VEC2, targetSize)
PUSH_CONSTANT(FLOAT, randomScale)
FRAGMENT_OUT(0, VEC4, hitData)
FRAGMENT_OUT(1, FLOAT, hitDepth)
FRAGMENT_SOURCE("effect_reflection_trace_frag.glsl")
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_reflection_resolve_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_reflection_resolve)
ADDITIONAL_INFO(eevee_legacy_surface_lib_step_resolve)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_raytrace_lib)
ADDITIONAL_INFO(eevee_legacy_lightprobe_lib)
ADDITIONAL_INFO(eevee_legacy_reflection_lib)
ADDITIONAL_INFO(eevee_legacy_closure_eval_glossy_lib)
ADDITIONAL_INFO(draw_fullscreen)
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, normalBuffer)
SAMPLER(2, FLOAT_2D, specroughBuffer)
SAMPLER(3, FLOAT_2D, hitBuffer)
SAMPLER(4, FLOAT_2D, hitDepth)
PUSH_CONSTANT(INT, samplePoolOffset)
FRAGMENT_OUT(0, VEC4, FragColor)
FRAGMENT_SOURCE("effect_reflection_resolve_frag.glsl")
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* Split reflection resolve support for Intel-based MacBooks. */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_reflection_resolve_probe)
DEFINE("RESOLVE_PROBE")
ADDITIONAL_INFO(eevee_legacy_effect_reflection_resolve)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_effect_reflection_resolve_ssr)
DEFINE("RESOLVE_SSR")
ADDITIONAL_INFO(eevee_legacy_effect_reflection_resolve)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_subsurface_first_pass_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_shader_effect_subsurface_common)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_common_lib)
FRAGMENT_OUT(0, VEC4, sssRadiance)
FRAGMENT_SOURCE("effect_subsurface_frag.glsl")
UNIFORM_BUF(0, SSSProfileBlock, sssProfile)
SAMPLER(0, DEPTH_2D, depthBuffer)
SAMPLER(1, FLOAT_2D, sssIrradiance)
SAMPLER(2, FLOAT_2D, sssRadius)
SAMPLER(3, FLOAT_2D, sssAlbedo)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_shader_effect_subsurface_common_FIRST_PASS)
DEFINE("FIRST_PASS")
ADDITIONAL_INFO(eevee_legacy_shader_effect_subsurface_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_shader_effect_subsurface_common_SECOND_PASS)
DEFINE("SECOND_PASS")
ADDITIONAL_INFO(eevee_legacy_shader_effect_subsurface_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_subsurface_translucency_sh_get */

GPU_SHADER_CREATE_INFO(eevee_legacy_shader_effect_subsurface_translucency)
DEFINE("EEVEE_TRANSLUCENCY")
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(eevee_legacy_lights_lib)
FRAGMENT_SOURCE("effect_translucency_frag.glsl")
FRAGMENT_OUT(0, VEC4, FragColor)
SAMPLER(1, DEPTH_2D, depthBuffer)
SAMPLER(1, FLOAT_1D, sssTexProfile)
SAMPLER(1, FLOAT_2D, sssRadius)
SAMPLER(1, FLOAT_2D_ARRAY, sssShadowCubes)
SAMPLER(1, FLOAT_2D_ARRAY, sssShadowCascades)
UNIFORM_BUF(0, SSSProfileBlock, sssProfile)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_renderpasses_post_process_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_post_process)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_lib)
FRAGMENT_SOURCE("renderpass_postprocess_frag.glsl")
PUSH_CONSTANT(INT, postProcessType)
PUSH_CONSTANT(INT, currentSample)
SAMPLER(0, DEPTH_2D, depthBuffer)
SAMPLER(1, FLOAT_2D, inputBuffer)
SAMPLER(2, FLOAT_2D, inputSecondLightBuffer)
SAMPLER(3, FLOAT_2D, inputColorBuffer)
SAMPLER(4, FLOAT_2D, inputTransmittanceBuffer)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_renderpasses_accumulate_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_renderpass_accumulate)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("renderpass_accumulate_frag.glsl")
SAMPLER(1, FLOAT_2D, inputBuffer)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_mist_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_mist_FIRST_PASS)
DEFINE("FIRST_PASS")
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_common_lib)
FRAGMENT_SOURCE("effect_mist_frag.glsl")
PUSH_CONSTANT(VEC3, mistSettings)
SAMPLER(0, DEPTH_2D, depthBuffer)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_ggx_lut_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_ggx_lut_bsdf)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
FRAGMENT_SOURCE("bsdf_lut_frag.glsl")
PUSH_CONSTANT(FLOAT, sampleCount)
FRAGMENT_OUT(0, VEC2, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_ggx_lut_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_ggx_lut_btdf)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
FRAGMENT_SOURCE("btdf_lut_frag.glsl")
PUSH_CONSTANT(FLOAT, sampleCount)
PUSH_CONSTANT(FLOAT, z_factor)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* Cryptomatte */
GPU_SHADER_CREATE_INFO(eevee_legacy_cryptomatte_common)
ADDITIONAL_INFO(eevee_legacy_closure_type_lib)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_cryptomatte_lib)
PUSH_CONSTANT(VEC4, cryptohash)
FRAGMENT_OUT(0, VEC4, FragColor)
VERTEX_SOURCE("cryptomatte_vert.glsl")
FRAGMENT_SOURCE("cryptomatte_frag.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_cryptomatte_hair)
DEFINE("HAIR_SHADER")
DEFINE("NO_ATTRIB_LOAD")
ADDITIONAL_INFO(eevee_legacy_cryptomatte_common)
ADDITIONAL_INFO(eevee_legacy_mateiral_surface_vert_hair)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_cryptomatte_mesh)
DEFINE("MESH_SHADER")
DEFINE("NO_ATTRIB_LOAD")
ADDITIONAL_INFO(eevee_legacy_cryptomatte_common)
ADDITIONAL_INFO(eevee_legacy_material_surface_vert)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()
