/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#include "gpu_shader_create_info.hh"

/* DOF Lib */
GPU_SHADER_CREATE_INFO(eevee_legacy_dof_lib)
ADDITIONAL_INFO(draw_view)
PUSH_CONSTANT(VEC4, cocParams)
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_bokeh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_bokeh)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_bokeh_frag.glsl")
PUSH_CONSTANT(FLOAT, bokehSides)
PUSH_CONSTANT(FLOAT, bokehRotation)
PUSH_CONSTANT(VEC2, bokehAnisotropyInv)
FRAGMENT_OUT(0, VEC2, outGatherLut)
FRAGMENT_OUT(1, FLOAT, outScatterLut)
FRAGMENT_OUT(2, FLOAT, outResolveLut)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_setup_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_setup)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_setup_frag.glsl")
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, DEPTH_2D, depthBuffer)
PUSH_CONSTANT(FLOAT, bokehMaxSize)
FRAGMENT_OUT(0, VEC4, outColor)
FRAGMENT_OUT(1, VEC2, outCoc)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_flatten_tiles_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_flatten_tiles)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_flatten_tiles_frag.glsl")
SAMPLER(0, FLOAT_2D, halfResCocBuffer)
FRAGMENT_OUT(0, VEC4, outFgCoc)
FRAGMENT_OUT(1, VEC3, outBgCoc)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_dilate_tiles_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_dilate_tiles_common)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_dilate_tiles_frag.glsl")
PUSH_CONSTANT(INT, ringCount)
PUSH_CONSTANT(INT, ringWidthMultiplier)
PUSH_CONSTANT(BOOL, dilateSlightFocus)
SAMPLER(0, FLOAT_2D, cocTilesFgBuffer)
SAMPLER(1, FLOAT_2D, cocTilesBgBuffer)
FRAGMENT_OUT(0, VEC4, outFgCoc)
FRAGMENT_OUT(1, VEC3, outBgCoc)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_dilate_tiles_MINMAX)
DEFINE("DILATE_MODE_MIN_MAX")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_dilate_tiles_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_dilate_tiles_MINABS)
DEFINE("DILATE_MODE_MIN_ABS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_dilate_tiles_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_downsample_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_downsample)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_downsample_frag.glsl")
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, cocBuffer)
FRAGMENT_OUT(0, VEC4, outColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_reduce_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_reduce_common)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_reduce_frag.glsl")
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, cocBuffer)
SAMPLER(2, FLOAT_2D, downsampledBuffer)
PUSH_CONSTANT(VEC2, bokehAnisotropy)
PUSH_CONSTANT(FLOAT, scatterColorThreshold)
PUSH_CONSTANT(FLOAT, scatterCocThreshold)
PUSH_CONSTANT(FLOAT, scatterColorNeighborMax)
PUSH_CONSTANT(FLOAT, colorNeighborClamping)
FRAGMENT_OUT(0, VEC4, outColor)
FRAGMENT_OUT(1, FLOAT, outCoc)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_reduce_COPY_PASS)
DEFINE("COPY_PASS")
FRAGMENT_OUT(2, VEC3, outScatterColor)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_reduce_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_reduce_REDUCE_PASS)
DEFINE("REDUCE_PASS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_reduce_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_gather_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_common)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_gather_frag.glsl")
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, cocBuffer)
SAMPLER(2, FLOAT_2D, colorBufferBilinear)
SAMPLER(3, FLOAT_2D, cocTilesFgBuffer)
SAMPLER(4, FLOAT_2D, cocTilesBgBuffer)
SAMPLER(5, FLOAT_2D, bokehLut)
PUSH_CONSTANT(VEC2, gatherInputUvCorrection)
PUSH_CONSTANT(VEC2, gatherOutputTexelSize)
PUSH_CONSTANT(VEC2, bokehAnisotropy)
FRAGMENT_OUT(0, VEC4, outColor)
FRAGMENT_OUT(1, FLOAT, outWeight)
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_bokeh)
DEFINE("DOF_BOKEH_TEXTURE")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_FOREGROUND)
DEFINE("DOF_FOREGROUND_PASS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_common)
FRAGMENT_OUT(2, VEC2, outOcclusion) /* NOT DOF_HOLEFILL_PASS */
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_BACKGROUND)
DEFINE("DOF_BACKGROUND_PASS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_common)
FRAGMENT_OUT(2, VEC2, outOcclusion) /* NOT DOF_HOLEFILL_PASS */
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_HOLEFILL)
DEFINE("DOF_BACKGROUND_PASS")
DEFINE("DOF_HOLEFILL_PASS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_FOREGROUND_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_bokeh)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_FOREGROUND)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_BACKGROUND_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_bokeh)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_BACKGROUND)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_gather_HOLEFILL_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_bokeh)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_gather_HOLEFILL)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_filter_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_filter)
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_filter_frag.glsl")
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, weightBuffer)
FRAGMENT_OUT(0, VEC4, outColor)
FRAGMENT_OUT(1, FLOAT, outWeight)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_scatter_get */
GPU_SHADER_INTERFACE_INFO(eevee_legacy_dof_scatter_iface)
FLAT(VEC4, color1)
FLAT(VEC4, color2)
FLAT(VEC4, color3)
FLAT(VEC4, color4)
FLAT(VEC4, weights)
FLAT(VEC4, cocs)
FLAT(VEC2, spritepos)
FLAT(FLOAT, spritesize)
GPU_SHADER_INTERFACE_END()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_scatter_common)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
VERTEX_SOURCE("effect_dof_scatter_vert.glsl")
FRAGMENT_SOURCE("effect_dof_scatter_frag.glsl")
VERTEX_OUT(eevee_legacy_dof_scatter_iface)
PUSH_CONSTANT(VEC2, targetTexelSize)
PUSH_CONSTANT(INT, spritePerRow)
PUSH_CONSTANT(VEC2, bokehAnisotropy)
PUSH_CONSTANT(VEC2, bokehAnisotropyInv)
SAMPLER(0, FLOAT_2D, colorBuffer)
SAMPLER(1, FLOAT_2D, cocBuffer)
SAMPLER(2, FLOAT_2D, occlusionBuffer)
SAMPLER(3, FLOAT_2D, bokehLut)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_scatter_bokeh)
DEFINE("DOF_BOKEH_TEXTURE")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_scatter_FOREGROUND)
DEFINE("DOF_FOREGROUND_PASS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_scatter_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_scatter_BACKGROUND)
DEFINE("DOF_BACKGROUND_PASS")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_scatter_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_scatter_FOREGROUND_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_scatter_bokeh)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_scatter_FOREGROUND)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_scatter_BACKGROUND_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_scatter_bokeh)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_scatter_BACKGROUND)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_depth_of_field_resolve_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_resolve_common)
DEFINE("DOF_RESOLVE_PASS")
ADDITIONAL_INFO(draw_fullscreen)
ADDITIONAL_INFO(eevee_legacy_defines_info)
ADDITIONAL_INFO(eevee_legacy_common_utiltex_lib)
ADDITIONAL_INFO(eevee_legacy_dof_lib)
FRAGMENT_SOURCE("effect_dof_resolve_frag.glsl")
SAMPLER(0, FLOAT_2D, fullResColorBuffer)
SAMPLER(1, DEPTH_2D, fullResDepthBuffer)
SAMPLER(2, FLOAT_2D, bgColorBuffer)
SAMPLER(3, FLOAT_2D, bgWeightBuffer)
SAMPLER(4, FLOAT_2D, bgTileBuffer)
SAMPLER(5, FLOAT_2D, fgColorBuffer)
SAMPLER(6, FLOAT_2D, fgWeightBuffer)
SAMPLER(7, FLOAT_2D, fgTileBuffer)
SAMPLER(8, FLOAT_2D, holefillColorBuffer)
SAMPLER(9, FLOAT_2D, holefillWeightBuffer)
SAMPLER(10, FLOAT_2D, bokehLut)
PUSH_CONSTANT(FLOAT, bokehMaxSize)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_resolve_bokeh)
DEFINE("DOF_BOKEH_TEXTURE")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_resolve_HQ)
DEFINE_VALUE("DOF_SLIGHT_FOCUS_DENSITY", "4")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_resolve_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_resolve_LQ)
DEFINE_VALUE("DOF_SLIGHT_FOCUS_DENSITY", "2")
ADDITIONAL_INFO(eevee_legacy_depth_of_field_resolve_common)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_resolve_HQ_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_resolve_HQ)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_resolve_bokeh)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_depth_of_field_resolve_LQ_BOKEH)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_resolve_LQ)
ADDITIONAL_INFO(eevee_legacy_depth_of_field_resolve_bokeh)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()
